export const elements = {
        SignupLoginBtn: () => cy.get('a[href="/login"]'),
        Loginemail: () => cy.get('[name="email"][data-qa="login-email"]'),
        LoginPassword: () => cy.get('[data-qa="login-password"]'),
        LoginBtn: () => cy.get('[data-qa="login-button"]'),
        WomenCategory: () => cy.get('[href="#Women"]'),
        DressBtn: () => cy.get('[href="/category_products/1"]'),
        PoloSelect: () => cy.get('.nav-stacked li:nth-of-type(1)'),
        GreenPoloTop: () => cy.get('.productinfo.text-center'),
        GreenTopAddToCart: () => cy.get('.productinfo [data-product-id="8"]'),
        BluePoloTop: () => cy.get('.productinfo.text-center'),
        BlueTopAddToCart: () => cy.get('.productinfo [data-product-id="1"]'),
        ContinueShoppingBtn: () => cy.get('[class="btn btn-success close-modal btn-block"]'),
        ViewCartBtn: () => cy.get('[class="modal-content"] a'),
        CheckoutBtn: () => cy.get('[class="btn btn-default check_out"]'),
        PlaceOrderBrn: () => cy.get('a[href="/payment"]'),
        CardNameInput: () => cy.get('[name="name_on_card"]'),
        CardNumInput: () => cy.get('[data-qa="card-number"]'),
        CVC: () => cy.get('[class="form-control card-cvc"]'),
        Month:() => cy.get('[data-qa="expiry-month"]'),
        Year: () => cy.get('[name="expiry_year"]'),
        PayandConfirm: () => cy.get('#submit'),
        OrderSuccess: () => cy.get('#form * p')

    }